version: '3'

services:
###> doctrine/doctrine-bundle ###
  db:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    container_name: langileak_mailer
    image: schickling/mailcatcher
    ports:
        - 1025:1025
        - 1080:1080
###< symfony/mailer ###
