version:  '3.7'
services:
    db:
        container_name: langileak_db
        image: postgres:${POSTGRES_VERSION:-13}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        ports:
            - "5432:5432"
        volumes:
            - v_langileak_db:/var/lib/postgresql/data:rw

    app:
        container_name: langileak_app
        env_file: ./.env.local
        extra_hosts:
            -   "host.docker.internal:host-gateway"
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - DOCKER_TIMEZONE=${DOCKER_TIMEZONE}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - DEBUGMODE=${DEBUGMODE}
                - FOSJSDUMP=${FOSJSDUMP}
        user: "675847499:675807745"
        depends_on:
            - db
            - redis
        volumes:
            - '.:/usr/src/app'
            - './docker/php/conf/php.ini:/usr/local/etc/php/php.ini:ro'
            - './docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro'
            - './docker/uploads/:/usr/src/app/public/uploads'
        working_dir: /usr/src/app

    nginx:
        container_name: langileak_nginx
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        depends_on:
            - app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
            - './docker/ssl/:/etc/nginx/ssl/'
        volumes_from:
            -   app
        working_dir: /usr/src/app

    redis:
        container_name: langileak_redis
        image: redis:alpine
        ports:
            - "6380:637"
        volumes:
            - v_langileak_redis:/data

volumes:
    v_langileak_db:
    v_langileak_redis:

networks:
    default:
        ipam:
            config:
                - subnet: 172.201.0.0/16
